 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/website-staging:$COMMIT_SHA', '.']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/website-staging:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'website-staging'
   - '--image'
   - 'gcr.io/$PROJECT_ID/website-staging:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--min-instances'
   - '0'
   - '--max-instances'
   - '1'
   - '--set-env-vars'
   - '[DGG_STATS_DB=dgg_stats_staging.db]'
 images:
 - 'gcr.io/$PROJECT_ID/website-staging:$COMMIT_SHA'